### ISSUE TITLE
Ошибка при добавлении сладостей в новогодний подарок

### ISSUE THREAD

**Issue by ghost** [Giruch1221/giruch_lab6#2]
Не все объекты могут быть добавлены в подарок. Требуется исправить границы задания случайного числа (увеличить на два
![1](https://cloud.githubusercontent.com/assets/29053253/26676123/aee99048-46f0-11e7-91b3-466923219280.jpg)
).

**Comment by Giruch1221** [comment]
Ошибка исправлена 
![image](https://cloud.githubusercontent.com/assets/29053251/26676297/5ec23d94-46f1-11e7-9c5f-f887c25a271c.png)

**Comment by ghost** [comment]
Отлично, новых ошибок не обнаружено!
